/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: e14848f3ddd3be7b6d1243fe8e8cebc5)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "CodeReviewAgent";
	}
	interface Env {
		AI: Ai;
		DB: D1Database;
		CodeReviewAgent: DurableObjectNamespace<import("./src/server").CodeReviewAgentV2>;
		CF_ACCOUNT_ID: string;
		CF_API_TOKEN: string;
	}
}
interface Env extends Cloudflare.Env {}
